### ISSUE TITLE
error when using it with gitlab-ci: `/bin/sh: /bin/sh: cannot execute binary file`

### ISSUE THREAD

**Issue by Mazuh** [dseg/node7-python2-pip-yarn-alpine35#1]
I was trying to follow along this tutorial https://medium.com/blechatech/continuous-deployment-of-a-react-app-to-aws-s3-via-bitbucket-pipelines-ccce7a2a7f1e

but my gitlab pipeline fails and I get this output (the error in at the end of it):

```
Running with gitlab-runner 11.5.0-rc1 (e900028d)
  on docker-auto-scale ed2dce3a
Using Docker executor with image dseg/node7-python2-pip-yarn-alpine35 ...
Pulling docker image dseg/node7-python2-pip-yarn-alpine35 ...
Using docker image sha256:798859cb048f8ca04723091104573a902c03fef4de6a1d530b34a05a3b81c09f for dseg/node7-python2-pip-yarn-alpine35 ...
Running on runner-ed2dce3a-project-9460485-concurrent-0 via runner-ed2dce3a-srm-1542489364-304869a9...
Cloning repository...
Cloning into '/builds/Mazuh/aws-deploy-test'...
Checking out 760c6bb5 as master...
Skipping Git submodules setup
/bin/sh: /bin/sh: cannot execute binary file
/bin/sh: /bin/sh: cannot execute binary file
ERROR: Job failed: exit code 126
```

here's my `.gitlab-ci.yml`, nothing unusual:

```yml
image: dseg/node7-python2-pip-yarn-alpine35

stages:
  - deploy

deployingDev:
  stage: deploy
  only:
    - master
  script:
    - yarn install
    - yarn build
    - yarn test
    - pip install awscli
    - # ... the rest, when I make this work, shall be the deploy itself using the awscli
```

and it looks like related to this gitlab-runner discussion: https://gitlab.com/gitlab-org/gitlab-runner/issues/2109
